/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrincipalGUI;

import GUI.ComprasGUI;
import GUIvendedor.BoletaDeReparaciones;
import GUIvendedor.BoletaDeVenta;
import GUIvendedor.CajaGUI;
import GUIvendedor.productosG;
import ReportesPack.iReportes;
import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        this.setUndecorated(true);
        initComponents();
         setTitle("AltoParlante");
        setLocationRelativeTo(this);
        setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
    }
    
    
    public Image getIconImage() {
        Image imagen = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenAP/LogoSistema.png"));
        return imagen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new org.edisoncor.gui.button.ButtonTask();
        jPanel3 = new javax.swing.JPanel();
        btnVender = new org.edisoncor.gui.button.ButtonTask();
        btnReparaciones = new org.edisoncor.gui.button.ButtonTask();
        btnCaja = new org.edisoncor.gui.button.ButtonTask();
        btnComprar = new org.edisoncor.gui.button.ButtonTask();
        btnReportes = new org.edisoncor.gui.button.ButtonTask();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setBorder(null);
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atraz.PNG"))); // NOI18N
        btnSalir.setText("Cerrar Session");
        btnSalir.setBorderPainted(false);
        btnSalir.setColorDeBorde(new java.awt.Color(0, 0, 0));
        btnSalir.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));
        btnSalir.setDefaultCapable(false);
        btnSalir.setDescription(" ");
        btnSalir.setRequestFocusEnabled(false);
        btnSalir.setRolloverEnabled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 220, 41));

        jPanel3.setBackground(new java.awt.Color(204, 255, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel3.setOpaque(false);

        btnVender.setBackground(new java.awt.Color(255, 255, 255));
        btnVender.setForeground(new java.awt.Color(255, 0, 51));
        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addRCompra.png"))); // NOI18N
        btnVender.setText("Realizar Venta");
        btnVender.setContentAreaFilled(true);
        btnVender.setDefaultCapable(false);
        btnVender.setDescription(" ");
        btnVender.setFocusable(false);
        btnVender.setRequestFocusEnabled(false);
        btnVender.setRolloverEnabled(false);
        btnVender.setVerifyInputWhenFocusTarget(false);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        btnReparaciones.setForeground(new java.awt.Color(255, 0, 51));
        btnReparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reparaciones.png"))); // NOI18N
        btnReparaciones.setText("Realizar Pedido");
        btnReparaciones.setAlignmentX(1.0F);
        btnReparaciones.setAlignmentY(1.0F);
        btnReparaciones.setAnchoDeBorde(5.0F);
        btnReparaciones.setContentAreaFilled(true);
        btnReparaciones.setDefaultCapable(false);
        btnReparaciones.setDescription(" ");
        btnReparaciones.setFocusPainted(true);
        btnReparaciones.setFocusable(false);
        btnReparaciones.setIconTextGap(8);
        btnReparaciones.setRequestFocusEnabled(false);
        btnReparaciones.setRolloverEnabled(false);
        btnReparaciones.setVerifyInputWhenFocusTarget(false);
        btnReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReparacionesActionPerformed(evt);
            }
        });

        btnCaja.setBackground(new java.awt.Color(255, 255, 255));
        btnCaja.setForeground(new java.awt.Color(255, 0, 51));
        btnCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/caja.png"))); // NOI18N
        btnCaja.setText("Caja");
        btnCaja.setContentAreaFilled(true);
        btnCaja.setDefaultCapable(false);
        btnCaja.setDescription(" ");
        btnCaja.setEnabled(false);
        btnCaja.setFocusable(false);
        btnCaja.setRequestFocusEnabled(false);
        btnCaja.setRolloverEnabled(false);
        btnCaja.setVerifyInputWhenFocusTarget(false);
        btnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajaActionPerformed(evt);
            }
        });

        btnComprar.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnComprar.setForeground(new java.awt.Color(255, 51, 51));
        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/images.png"))); // NOI18N
        btnComprar.setText("Registrar Compras");
        btnComprar.setBorderPainted(false);
        btnComprar.setColorDeBorde(new java.awt.Color(204, 204, 255));
        btnComprar.setContentAreaFilled(true);
        btnComprar.setDefaultCapable(false);
        btnComprar.setDescription(" ");
        btnComprar.setEnabled(false);
        btnComprar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnComprar.setRequestFocusEnabled(false);
        btnComprar.setRolloverEnabled(false);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReportes.setForeground(new java.awt.Color(255, 0, 51));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reportes.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setColorDeBorde(new java.awt.Color(204, 204, 255));
        btnReportes.setContentAreaFilled(true);
        btnReportes.setDescription(" ");
        btnReportes.setRequestFocusEnabled(false);
        btnReportes.setRolloverEnabled(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 390, 510));

        jLabel2.setText("Michael Anthony Apaza C");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, 19));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenAP/FondoMP.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        new Logeo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed

        new BoletaDeVenta(this, true).setVisible(true);
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReparacionesActionPerformed
        new BoletaDeReparaciones(this, true).setVisible(true);
    }//GEN-LAST:event_btnReparacionesActionPerformed

    private void btnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajaActionPerformed
        new CajaGUI(this, true).setVisible(true);
    }//GEN-LAST:event_btnCajaActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        new ComprasGUI(this, true).setVisible(true);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        new iReportes().setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask btnCaja;
    private org.edisoncor.gui.button.ButtonTask btnComprar;
    private org.edisoncor.gui.button.ButtonTask btnReparaciones;
    private org.edisoncor.gui.button.ButtonTask btnReportes;
    private org.edisoncor.gui.button.ButtonTask btnSalir;
    private org.edisoncor.gui.button.ButtonTask btnVender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
private void Close() {
        int Salir = JOptionPane.showConfirmDialog(null, "¿Desea realmente salir del Sistema?", "Salir del sistema", 2);
        if (JOptionPane.YES_NO_OPTION == Salir) {
            System.exit(0);
        } else {

        }
    }
}
